### ISSUE TITLE
tqdm install required

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/chempfn#38]
Hi @DhanshreeA !

If I install chempfn using

`pip install git+https://github.com/ersilia-os/chempfn.git`

and I try to use the AntimicrobialsDataLoader I get the following error

`ModuleNotFoundError: No module named 'tqdm'`

should we specify tqdm as requirement?

**Comment by DhanshreeA** [comment]
Hi @GemmaTuron , chempfn has 3 types of dependencies: main dependencies, test, and dev. Within test, we have PyTDC which in turn has tqdm as a dependency. If you install chempfn as `pip install ".[test]"`, assuming you are in the chempfn directory, you should have tqdm in your environment. This is not a good solution though since we now explicitly use tqdm in the evaluate method. I'll add tqdm as an explicit dependency.

**Comment by GemmaTuron** [comment]
ah makes sense
I did not check the [test] installation dependencies sorry
Feel free to close the issue when solved

**Comment by DhanshreeA** [comment]
Solved in e4e0fbe704c4d82f07740eb5e11085151398ef2a
